name: 'Modpack Utils'
description: 'Modpack Utils'
inputs:
   actions:
      description: 'The actions to perform. can be any of [web, curseforge]'
      required: true
   api_url:
      description: 'The remote url of the web api'
      required: false
      default: 'https://packs.somethingcatchy.net/api'
   web_token:
      description: 'The web api token'
      required: false
   release_version:
      description: 'Custom release version'
      required: false
   release_type:
      description: 'Custom release type. [alpha, beta, release]'
      required: false
   curseforge_token:
      description: 'The curseforge access token'
      required: false
   curseforge_project:
      description: 'The curseforge project ID'
      required: false
runs:
   using: 'node16'
   main: dist/index.js
branding:
   color: 'purple'
   icon: 'arrow-up-circle'
